# Generated by Django 4.0.4 on 2022-05-25 18:14

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('categorie', models.CharField(max_length=200)),
                ('media', models.FileField(blank=True, upload_to=posts.models.load_media)),
                ('image', models.ImageField(blank=True, upload_to=posts.models.load_media)),
                ('image1', models.ImageField(blank=True, upload_to=posts.models.load_media)),
                ('image2', models.ImageField(blank=True, upload_to=posts.models.load_media)),
                ('image3', models.ImageField(blank=True, upload_to=posts.models.load_media)),
                ('investi', models.CharField(choices=[('Investi', 'Investi'), ('Non', 'Non')], default='Non', max_length=10)),
                ('description', models.TextField(max_length=500, null=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='users.etudiant')),
            ],
        ),
    ]
