# Generated by Django 4.0.4 on 2022-06-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, default='post.jpg', upload_to='image/post_image/'),
        ),
    ]
