# Generated by Django 4.1 on 2022-09-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='etu',
            new_name='etudiant',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='inv',
            new_name='invest',
        ),
    ]
