# Generated by Django 4.0.4 on 2022-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/post_image/'),
        ),
    ]
