# Generated by Django 4.0.4 on 2022-06-14 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_post',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date_post'),
        ),
    ]
