# Generated by Django 4.0.4 on 2022-05-27 17:41

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, upload_to=posts.models.posts_image),
        ),
    ]
