# Generated by Django 4.0.4 on 2022-07-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_message_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commessage',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='favoris',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='favoris',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='commentaire',
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000000),
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='ComMessage',
        ),
        migrations.DeleteModel(
            name='Favoris',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
