# Generated by Django 4.0.4 on 2022-05-25 18:17

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_projet_image1_remove_projet_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image1',
            field=models.ImageField(blank=True, upload_to=posts.models.load_media),
        ),
        migrations.AddField(
            model_name='projet',
            name='image2',
            field=models.ImageField(blank=True, upload_to=posts.models.load_media),
        ),
        migrations.AddField(
            model_name='projet',
            name='image3',
            field=models.ImageField(blank=True, upload_to=posts.models.load_media),
        ),
    ]
