# Generated by Django 4.0.4 on 2022-06-16 01:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_time_com_alter_reponse_time_rep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='title',
            new_name='title_com',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_com',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 1, 15, 45, 520895, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='time_rep',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 1, 15, 45, 521556, tzinfo=utc)),
        ),
    ]
