# Generated by Django 4.1 on 2022-09-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_value_message_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='rooms',
        ),
    ]
