# Generated by Django 4.1 on 2022-09-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_room_message_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='rooms',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='values',
            new_name='value',
        ),
    ]
