# Generated by Django 4.0.4 on 2022-06-16 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_title_reponse_title_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_com',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 1, 18, 0, 175749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='time_rep',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 1, 18, 0, 176430, tzinfo=utc)),
        ),
    ]
