# Generated by Django 4.0.4 on 2022-05-26 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_projet_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
