# Generated by Django 4.0.4 on 2022-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, default='post.jpg', upload_to=''),
        ),
    ]
