# Generated by Django 4.0.4 on 2022-07-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='projet',
            new_name='projets',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='user',
            new_name='users',
        ),
    ]
