# Generated by Django 4.0.4 on 2022-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_projet_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/profile_media/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image1',
            field=models.ImageField(blank=True, upload_to='image/profile_media/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image2',
            field=models.ImageField(blank=True, upload_to='image/profile_media/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image3',
            field=models.ImageField(blank=True, upload_to='image/profile_media/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='investi',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=10),
        ),
        migrations.AlterField(
            model_name='projet',
            name='media',
            field=models.FileField(blank=True, upload_to='image/profile_media/'),
        ),
    ]
