# Generated by Django 4.0.4 on 2022-07-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_projet_commentaire_projets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='names',
        ),
    ]
