# Generated by Django 4.0.4 on 2022-06-16 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_time_com_alter_reponse_time_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_com',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 4, 16, 8, 804263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='time_rep',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 4, 16, 8, 804869, tzinfo=utc)),
        ),
    ]
