# Generated by Django 4.1 on 2022-09-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_etudiant_room_etud_rename_invest_room_inv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='etud',
            new_name='etu',
        ),
    ]
