# Generated by Django 4.0.4 on 2022-06-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_time_com_alter_reponse_time_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='title_com',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='user_reponse',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
