# Generated by Django 4.0.4 on 2022-07-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_projets_commentaire_projet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='names',
            new_name='name',
        ),
    ]
