# Generated by Django 4.0.4 on 2022-05-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image1',
            field=models.ImageField(blank=True, upload_to='image/post_image/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image3',
            field=models.ImageField(blank=True, upload_to='image/post_image/'),
        ),
    ]
