# Generated by Django 4.0.4 on 2022-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_projet_image1_alter_projet_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='media',
            field=models.FileField(blank=True, upload_to='documents/post_doc/'),
        ),
    ]
