# Generated by Django 4.0.4 on 2022-05-26 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_projet_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_post',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projet',
            name='investi',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=10),
        ),
    ]
