# Generated by Django 4.0.4 on 2022-05-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_projet_date_post_alter_projet_investi'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/post_image/'),
        ),
    ]
