# Generated by Django 4.0.4 on 2022-05-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_projet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='image',
        ),
    ]
