# Generated by Django 4.0.1 on 2022-04-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=200, null=True)),
                ('photo_profile', models.ImageField(blank=True, upload_to=users.models.load_image, verbose_name='Profile')),
                ('tel', models.IntegerField(verbose_name='telephone')),
                ('type_user', models.CharField(choices=[('Investisseur', 'Investisseur'), ('Etudiant', 'Etudiant')], default='Etudiant', max_length=20, null=True, verbose_name='type user')),
                ('niveauEtude', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master I', 'Master I'), ('Master II', 'Master II'), ('Doctorant', 'Doctorant')], default='Licence 1', max_length=30, verbose_name="Niveau D'Etude")),
                ('universite', models.CharField(max_length=100)),
                ('fiche_inscription', models.FileField(upload_to=users.models.load_image)),
                ('bio', models.TextField(max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=200, null=True)),
                ('photo_profile', models.ImageField(blank=True, upload_to=users.models.load_image, verbose_name='Profile')),
                ('tel', models.IntegerField(verbose_name='telephone')),
                ('type_user', models.CharField(choices=[('Investisseur', 'Investisseur'), ('Etudiant', 'Etudiant')], default='Etudiant', max_length=20, null=True, verbose_name='type user')),
                ('profession', models.CharField(max_length=70)),
                ('entreprise', models.CharField(max_length=100)),
                ('objectif', models.CharField(max_length=500)),
                ('etudiant', models.ManyToManyField(blank=True, related_name='investisseurs', to='users.Etudiant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
