# Generated by Django 4.0.1 on 2022-05-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
