# Generated by Django 4.0.4 on 2022-05-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='is_investor',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='investisseur',
            name='is_investor',
        ),
        migrations.RemoveField(
            model_name='investisseur',
            name='is_student',
        ),
    ]
