# Generated by Django 4.0.1 on 2022-05-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_etudiant_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisseur',
            name='objectifs',
            field=models.CharField(max_length=300),
        ),
    ]
