# Generated by Django 4.0.1 on 2022-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_etudiant_user_alter_investisseur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photoProfil',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='image/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='investisseur',
            name='photoProfil',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='image/profile_pics/'),
        ),
    ]
