# Generated by Django 4.0.4 on 2022-05-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_etudiant_bio_alter_etudiant_telephone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
