# Generated by Django 4.0.4 on 2022-06-16 03:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_alter_comment_time_com_alter_reponse_time_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=600)),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('time_com', models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 3, 56, 23, 618866, tzinfo=utc))),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.projet')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=600)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('time_rep', models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 3, 56, 23, 619386, tzinfo=utc))),
                ('title_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponse', to='publication.commentaire')),
                ('user_reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
