# Generated by Django 4.0.4 on 2022-06-16 04:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_alter_comment_time_com_alter_reponse_time_rep'),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time_com',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 4, 16, 8, 805423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reponses',
            name='time_rep',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 4, 16, 8, 805916, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_like', models.BigIntegerField(default=0, verbose_name='nombre de like')),
                ('Projet_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liskeProjet', to='posts.projet')),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
