# Generated by Django 4.0.4 on 2022-06-16 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_commentaire_time_com_alter_reponses_time_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time_com',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 4, 54, 46, 126460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reponses',
            name='time_rep',
            field=models.TimeField(auto_now_add=datetime.datetime(2022, 6, 16, 4, 54, 46, 127161, tzinfo=utc)),
        ),
    ]
